import React, { useState } from "react";
import {
  StyleSheet,
  View,
  Text,
  ScrollView,
  KeyboardAvoidingView,
  Platform,
} from "react-native";
import { useRouter } from "expo-router";
import { authClient } from "../../src/api/client";
import { useAuth } from "../../src/context/AuthContext";
import { colors, fonts, spacing } from "../../src/theme";
import { KeyRound, Key, CheckCircle2, ArrowLeft } from "lucide-react-native";
import { InputComponent } from "../../src/components/InputComponent";
import { ButtonComponent } from "../../src/components/ButtonComponent";

export default function TwoFactorChallengeScreen() {
  const router = useRouter();
  const { refreshSetup } = useAuth();

  const [code, setCode] = useState("");
  const [isBackupCode, setIsBackupCode] = useState(false);
  const [loading, setLoading] = useState(false);
  const [codeError, setCodeError] = useState<string | null>(null);
  const [generalError, setGeneralError] = useState<string | null>(null);

  const handleVerify = async () => {
    const cleanCode = code.trim();
    if (!cleanCode) {
      setCodeError(
        isBackupCode
          ? "Please enter your backup code."
          : "Please enter the 6-digit code from your authenticator app.",
      );
      return;
    }

    setLoading(true);
    setCodeError(null);
    setGeneralError(null);

    try {
      let response;
      if (isBackupCode) {
        response = await authClient.twoFactor.verifyBackupCode({
          code: cleanCode,
        });
      } else {
        response = await authClient.twoFactor.verifyTotp({
          code: cleanCode,
        });
      }

      if (response?.error) {
        setCodeError(
          response.error.message ||
            (isBackupCode
              ? "Invalid backup code. Please verify and try again."
              : "Invalid authenticator code. Please check your authenticator app."),
        );
        return;
      }

      // Sync updated account state
      const setup = await refreshSetup();

      if (setup) {
        if (!setup.emailVerified || setup.nextStep === "verify-email") {
          router.replace("/(auth)/verify-email");
          return;
        }

        if (!setup.profileComplete || setup.nextStep === "profile") {
          router.replace("/(app)/profile/setup");
          return;
        }

        router.replace("/(app)/(tabs)/home");
      } else {
        router.replace("/");
      }
    } catch (err: any) {
      console.error("2FA verification error", err);
      setGeneralError(
        err?.message || "Failed to verify security challenge. Please try again.",
      );
    } finally {
      setLoading(false);
    }
  };

  return (
    <KeyboardAvoidingView
      style={styles.keyboardContainer}
      behavior={Platform.OS === "ios" ? "padding" : undefined}
    >
      <ScrollView
        contentContainerStyle={styles.scrollContent}
        keyboardShouldPersistTaps="handled"
      >
        <View style={styles.header}>
          <Text style={styles.title}>
            {isBackupCode ? "Enter backup code" : "Two-factor verification"}
          </Text>
          <Text style={styles.subtitle}>
            {isBackupCode
              ? "Enter one of your emergency recovery backup codes to regain account access."
              : "Enter the current 6-digit security code generated by your authenticator app."}
          </Text>
        </View>

        {generalError ? (
          <View style={styles.errorBox}>
            <Text style={styles.errorBoxText}>{generalError}</Text>
          </View>
        ) : null}

        <View style={styles.form}>
          <InputComponent
            label={isBackupCode ? "Backup Recovery Code" : "Authenticator Code (TOTP)"}
            placeholder={isBackupCode ? "e.g. A1B2-C3D4" : "123456"}
            keyboardType={isBackupCode ? "default" : "number-pad"}
            maxLength={isBackupCode ? 30 : 6}
            autoCapitalize={isBackupCode ? "characters" : "none"}
            value={code}
            leftIcon={<KeyRound size={18} color={colors.textMuted} />}
            error={codeError}
            onChangeText={(text) => {
              setCode(text);
              if (codeError) setCodeError(null);
              if (generalError) setGeneralError(null);
            }}
          />

          <ButtonComponent
            title="Verify & Continue"
            icon={<CheckCircle2 size={18} color={colors.white} />}
            onPress={handleVerify}
            loading={loading}
            style={styles.submitButton}
          />

          <ButtonComponent
            title={
              isBackupCode
                ? "Use Authenticator App (TOTP) instead"
                : "Cannot access authenticator? Use a backup code"
            }
            icon={<Key size={16} color={colors.primary} />}
            variant="ghost"
            onPress={() => {
              setIsBackupCode((prev) => !prev);
              setCode("");
              setCodeError(null);
              setGeneralError(null);
            }}
            style={styles.toggleButton}
            textStyle={styles.toggleText}
          />
        </View>

        <View style={styles.footer}>
          <ButtonComponent
            title="Back to Sign In"
            icon={<ArrowLeft size={16} color={colors.primary} />}
            variant="ghost"
            onPress={() => router.replace("/(auth)/login")}
            textStyle={styles.backLinkText}
          />
        </View>
      </ScrollView>
    </KeyboardAvoidingView>
  );
}

const styles = StyleSheet.create({
  keyboardContainer: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.xxl,
    paddingBottom: spacing.xxl,
    justifyContent: "center",
  },
  header: {
    marginBottom: spacing.xl,
  },
  title: {
    fontFamily: fonts.heading.bold,
    fontSize: 28,
    color: colors.text,
    marginBottom: spacing.xs,
  },
  subtitle: {
    fontFamily: fonts.body.regular,
    fontSize: 15,
    color: colors.textMuted,
    lineHeight: 22,
  },
  errorBox: {
    backgroundColor: "rgba(184, 84, 80, 0.1)",
    borderWidth: 1,
    borderColor: colors.error,
    borderRadius: 8,
    padding: spacing.md,
    marginBottom: spacing.base,
  },
  errorBoxText: {
    color: colors.error,
    fontSize: 13,
    fontWeight: "500",
  },
  form: {
    marginBottom: spacing.xl,
  },
  submitButton: {
    marginTop: spacing.sm,
  },
  toggleButton: {
    marginTop: spacing.md,
  },
  toggleText: {
    fontSize: 14,
    color: colors.primary,
    fontWeight: "600",
  },
  footer: {
    alignItems: "center",
    marginTop: spacing.base,
  },
  backLinkText: {
    color: colors.textMuted,
    fontSize: 14,
  },
});
