// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/dist/lib/metadata/types/metadata-interface.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type PagesPageConfig = {
  default: React.ComponentType<any> | ((props: any) => React.ReactNode | Promise<React.ReactNode> | never | void)
  getStaticProps?: (context: any) => Promise<any> | any
  getStaticPaths?: (context: any) => Promise<any> | any
  getServerSideProps?: (context: any) => Promise<any> | any
  getInitialProps?: (context: any) => Promise<any> | any
  /**
   * Segment configuration for legacy Pages Router pages.
   * Validated at build-time by parsePagesSegmentConfig.
   */
  config?: {
    amp?: boolean | 'hybrid' | string // necessary for JS
    maxDuration?: number
    runtime?: 'edge' | 'experimental-edge' | 'nodejs' | string // necessary unless config is exported as const
    regions?: string[]
  }
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ..\..\app\(auth)\login\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(auth)\\login\\page.js")
  handler satisfies AppPageConfig<"/login">
}

// Validate ..\..\app\(auth)\signup\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(auth)\\signup\\page.js")
  handler satisfies AppPageConfig<"/signup">
}

// Validate ..\..\app\(auth)\verify-email\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(auth)\\verify-email\\page.js")
  handler satisfies AppPageConfig<"/verify-email">
}

// Validate ..\..\app\admin\performance\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\admin\\performance\\page.js")
  handler satisfies AppPageConfig<"/admin/performance">
}

// Validate ..\..\app\cart\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\cart\\page.js")
  handler satisfies AppPageConfig<"/cart">
}

// Validate ..\..\app\marketplace\[id]\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\marketplace\\[id]\\page.js")
  handler satisfies AppPageConfig<"/marketplace/[id]">
}

// Validate ..\..\app\marketplace\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\marketplace\\page.js")
  handler satisfies AppPageConfig<"/marketplace">
}

// Validate ..\..\app\orders\[id]\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\orders\\[id]\\page.js")
  handler satisfies AppPageConfig<"/orders/[id]">
}

// Validate ..\..\app\orders\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\orders\\page.js")
  handler satisfies AppPageConfig<"/orders">
}

// Validate ..\..\app\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\page.js")
  handler satisfies AppPageConfig<"/">
}

// Validate ..\..\app\profile\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\profile\\page.js")
  handler satisfies AppPageConfig<"/profile">
}

// Validate ..\..\app\sellers\[id]\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\sellers\\[id]\\page.js")
  handler satisfies AppPageConfig<"/sellers/[id]">
}

// Validate ..\..\app\stakeholder\summary\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\stakeholder\\summary\\page.js")
  handler satisfies AppPageConfig<"/stakeholder/summary">
}



// Validate ..\..\pages\_document.tsx
{
  const handler = {} as typeof import("..\\..\\pages\\_document.js")
  handler satisfies PagesPageConfig
}



// Validate ..\..\app\layout.tsx
{
  const handler = {} as typeof import("..\\..\\app\\layout.js")
  handler satisfies LayoutConfig<"/">
}
